keys:
  # Homelab age key (private key: /var/lib/sops-nix/key.txt on homelab)
  - &homelab age1dgk5vje03df43n6qrvvsth87v5fyx4rk9cv6m0u5gqwevq4kgqspzc5nr

  # Local machine key (private key: ~/.config/sops/age/keys.txt on local machine)
  - &local age13mpmmp8ag6hltyumv86x48hmftzsu87ylkses5xwhxz6f0wnwd3qj9ylrn

  # Test key (for CI/VM tests - private key committed in tests/age-key.txt)
  - &test age1u5wcrsntpnqs4ldtm7hnjfumm4p0f5pazh9e95kqxn4m3uzp6pts2t7hhz

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *homelab
          - *local
          - *test
  - path_regex: tests/[^/]+\.yaml$
    key_groups:
      - age:
          - *test
