keys:
  # System age key (stored at /var/lib/sops-nix/key.txt on the target machine)
  # Generate with: mkdir -p /var/lib/sops-nix && nix run nixpkgs#age -- -generate -o /var/lib/sops-nix/key.txt
  - &homelab age1hl95qcnws8hjqwhrjj4hfs4wtvlcngkymmnx65lwl96muxzqeqhsfp8t0n

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *homelab
